name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v4

      - name: Setup Deno 🔧
        uses: denoland/setup-deno@v2
        with:
          deno-version: v1.x

      - name: Run linters and formatter checks 🚨
        run: |
          deno lint
          deno fmt --check
          deno check mod.ts
