name: ci

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout repo 🛎
        uses: actions/checkout@v3

      - name: Setup Deno 🔧
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run linters and formatter checks 🚨
        run: |
          deno lint
          deno fmt --check
          deno check mod.ts

      - name: Package 📦
        run: deno compile --allow-net --allow-env --allow-read --target x86_64-unknown-linux-gnu -o dist/calsync-x86_64-unknown-linux-gnu mod.ts

      - name: Upload artifact ⬆️
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3
        with:
          name: calsync-x86_64-unknown-linux-gnu
          path: dist/calsync-x86_64-unknown-linux-gnu
